## 2. NumPy

**NumPy**는 선형대수 기반 데이터/수치 분석 모듈입니다. 파이썬에서 여러 데이터를 연산할 때 for이나 while을 사용했습니다. 이런 형태를 loop라고 합니다. 순차적으로 데이터를 확인하고 연산합니다. list의 경우 내부 value의 dtype이 int, str, float 등 다른 형태의 데이터가 들어갈 수 있지만, numpy의 ndarray는 보통 같거나 유사한 자료형만 취급하기 때문에 메모리까지 도달하는 단계가 적습니다. 그만큼 빨라집니다.

numpy는 수치(숫자)로 된 데이터를 배열Array형식으로 인식하여 계산하면서 더 빨라집니다. 배열Array은 쉽게 말하면 n차원의 행렬matrix로 된 데이터입니다. NumPy가 빠른 이유는 메모리에 저장된 데이터에 접근할 때 단계가 적기 때문입니다. 

이번 커리큘럼의 목적은 "Python을 통한 데이터 수집/처리/시각화를 할 수 있다"이기 때문에 더 효율적인 연산, 공학적 효율성에 대한 설명은 각설합니다. 앞에 말씀드린 내용도 그냥 교양 수준으로 알고 계셔도 무방합니다.

NumPy는 Pandas의 처리를 돕는 도구이지, 분석도구는 아닙니다. NumPy 또한 내용이 방대합니다. 기초적인 데이터 분석에 필요한 내용만 추렸으니 더 필요하다면 구글링, 책을 통한 스터디를 추천드립니다.

그리고 그 즈음 되면 여러분이 많이 성장했다고 생각하셔도 좋을거예요:)

### NumPy import하기

In [ ]:
import numpy as np

### 2.1. 배열 생성 

#### 다차원 배열 ndarray

- NumPy의 중요 자료형
- 표준 파이썬의 array와 비슷하지만 별개임
- 다차원(Multi-dimentsion) 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음.

In [ ]:
list1 = [1,2,3]
print(type(list1))   # 파이썬의 list
array1 = np.array(list1)
print(type(array1))  # 넘파이의 ndarray

<class 'list'>
<class 'numpy.ndarray'>


- array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음.

In [ ]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array1.shape # 쉼표 뒤가 없다면 1차원이라는 의미 

(3,)

In [ ]:
# 2차원 ndarray 만들기 
array2 = np.array([[1,2,3],
                 [2,3,4]])
array2   # 항상 데이터를 보는 습관 들이기!

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
array2.shape # 2개의 row와 3개의 column

(2, 3)

#### 배열을 생성하는 array 함수
- **array()**: 데이터를 기반으로 배열(ndarray)를 생성하는 함수

In [ ]:
alist = [1,2.5,3,4.5,5]
arr1 = np.array(alist) # ndarray로 바꾸어준 것!
arr1

array([1. , 2.5, 3. , 4.5, 5. ])

In [ ]:
dalist = [[1,2,3,4,5],
         [6,7,8,9,10]]
arr2 = np.array(dalist)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 2.2. ndarray 속성

- **ndarray.ndim**: ndarray의 차원
- **ndarray.shape**: 배열의 모양
- **ndarray.size**: 배열의 원소의 개수
- **ndarray.dtype**: 원소의 자료형

In [ ]:
array1.ndim  # 1차원이구나!

1

In [ ]:
array2.ndim # 2차원이구나!

2

In [ ]:
array1.size # 전체 원소 개수 = 3

3

In [ ]:
array2.size

6

In [ ]:
array1.dtype

dtype('int32')

### 2.3. 난수 생성, 차원 변환

- np.arange(): range의 numpy 버전. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
- np.zeros(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
- np.ones(): 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray를 반환

- np.random.rand(): 균등 분포에서 추출
- np.random.randint(): 주어진 범위 내의 임의의 난수
- np.random.randn(): 표준편차가 1이고 평균 0인 정규 분포에서 추출
- np.random.normal(): 정규 분포에서 추출


- np.reshape(): ndarray를 특정 차원 및 크기로 변환


In [ ]:
# 꿀팁! 내가 잘 모르는 게 나왔다! 
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

이렇게 괄호 대신 ?를 적어주면 도움말이 뜹니다! 그러면 영어로 옵션값(파라미터들)도 볼 수 있고, 어떤 함수인지도 알 수 있습니다. 무엇보다 가장 좋은 것은 제일 아래에 examples를 통해 이 함수가 어떤 기능을 하는지 직관적으로 알 수 있어요!

In [ ]:
# np.arange()
# 예시를 하나 가져왔어요. 아, 이 함수는 파이썬의 range()와 비슷하구나~
np.arange(3)

array([0, 1, 2])

In [ ]:
sequence_array = np.arange(10)
sequence_array  # 항상 데이터 확인하는 것 잊지말기!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
sequence_array.shape  # 1차원이고, 칼럼이 10개네~!

(10,)

In [ ]:
# 퀴즈: 괄호 안의 3개의 숫자는 무엇을 의미할까요?
question = np.arange(0,10,2)
question

array([0, 2, 4, 6, 8])

In [ ]:
# np.zeros()
zero_array = np.zeros((3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
zero_array.shape

(3, 2)

In [ ]:
# np.ones()
one_array = np.ones((3,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
one_array.shape

(3, 2)

In [ ]:
# np.random.rand()
np.random.rand(10)  # 0~1 균일분포, 표준 정규분포의 난수를 생성

array([0.76928998, 0.03424426, 0.6322589 , 0.04665314, 0.84934759,
       0.04980584, 0.08289113, 0.51044719, 0.70186768, 0.72735719])

In [ ]:
np.random.rand(4,2) # 2차원

array([[0.06367154, 0.48136651],
       [0.18470819, 0.41477156],
       [0.58545537, 0.45293376],
       [0.34727256, 0.11004234]])

In [ ]:
#np.random.randint()
np.random.randint(10)   # 0 ~ 9의 무작위 숫자 1개 뽑기

6

In [ ]:
np.random.randint(1, 25)   # 1 ~ 24의 무작위 숫자 1개 뽑기

13

In [ ]:
# np.random.randn()
np.random.randn(10) # 평균0, 표준편차 1의 표준정규분포 난수 생성(10개)

array([ 1.13842801, -1.31188034, -0.4937574 , -0.08306181, -0.37268391,
        0.52199079,  0.14649055,  1.04724318,  1.14282212, -0.29280115])

In [ ]:
np.random.randn(4,2)    # (4,2)의 2차원 matrix

array([[-0.91436752,  0.50986916],
       [ 0.49658121,  0.50815474],
       [-2.28312695,  0.28571353],
       [ 1.06423767, -0.10832704]])

In [ ]:
# np.random.normal()
np.random.seed(seed=100)    # 다음번에 100 주면 똑같이 나와요!
np.random.normal(size = 5)  # 무작위 숫자 5개

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [ ]:
np.random.seed(seed=100)    # 똑같죠?
np.random.normal(size = 5)  

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [ ]:
np.random.seed(seed=100)    
np.random.normal(size = (4,2))  # (4,2)짜리 2차원 matrix로 만들기

array([[-1.74976547,  0.3426804 ],
       [ 1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884],
       [ 0.22117967, -1.07004333]])

In [ ]:
# np.reshape()
b = np.arange(12).reshape(4,3) # 4개의 로우, 3개의 컬럼으로!
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
c = np.arange(24).reshape(2,3,4) # 3차원으로 바꿔주세욤!
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 2.4. 수학/ 통계 매서드

- np.sum(): 전체 또는 특정 축의 원소의 합계
- np.mean(): 산술평균
- np.std(): 표준편차
- np.var(): 분산
- np.min(), max(): 최소값, 최대값
- np.cumsum(): 누적합
- np.cumprod(): 누적곱

In [ ]:
a = np.random.random((2,3))
a

array([[0.89132195, 0.20920212, 0.18532822],
       [0.10837689, 0.21969749, 0.97862378]])

In [ ]:
a.sum(axis=0)   # 열의 합(아래 방향)

array([0.99969884, 0.42889961, 1.163952  ])

In [ ]:
a.sum(axis=1)   # 행의 합(오른쪽 방향)

array([1.2858523 , 1.30669817])

In [ ]:
a.mean()

0.43209174396269096

In [ ]:
a.std()

0.35825137881615055

In [ ]:
a.var()

0.128344050423673

In [ ]:
a.min()

0.10837689046425514

In [ ]:
a.max()

0.9786237847073697

In [ ]:
a.cumsum(axis=1)  # 행의 누적합

array([[0.89132195, 1.10052408, 1.2858523 ],
       [0.10837689, 0.32807438, 1.30669817]])

In [ ]:
a.cumprod()

array([8.91321954e-01, 1.86466444e-01, 3.45574941e-02, 3.74523376e-03,
       8.22818466e-04, 8.05229721e-04])

In [ ]:
arr = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [ ]:
arr.cumsum(axis = 1) # column 방향으로~

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

numpy에서 axis=0은 row, axis=1은 column을 의미합니다. 그래서 column 방향이라고 한 것에 헷갈릴 수 있겠지만, 틀린 말이 아닙니다.

### 2.5. array 선택: Indexing & Slicing

#### Indexing
- []: 리스트 인덱싱과 같아요!
- 불린 인덱싱

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [ ]:
a[2]

8

In [ ]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [ ]:
a[:6:2] = -1000  #a[0:6:2]에 모두 -1000을 넣는다
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [ ]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [ ]:
# 다차원 ndarray의 인덱싱 
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [ ]:
arr2d[0,2]

3

#### Slicing

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [ ]:
# 다차원 ndarray의 슬라이싱
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d[:2,1:]  # 생략 되어 있다면 0부터!

array([[2, 3],
       [5, 6]])

#### Boolean Indexing

In [ ]:
array1d = np.arange(start=1, stop=10) #(1,10)과 같음
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# [ ] 안에 array1d > 5보다 높은 것만 가져오너라!
boolean_array1d = array1d[array1d > 5]
boolean_array1d

array([6, 7, 8, 9])

In [ ]:
array1d > 5 # 5이상이면 True로 표시

array([False, False, False, False, False,  True,  True,  True,  True])

여기까지가 수치 데이터 처리에 사용되는 NumPy였습니다! 지금 바로 당장에는 사용하지 않을 것 같아요. 당장에 많이 사용되는 것은 pandas겠지만 그래도 pandas 배우는 김에 numpy도 간단하게 배우고 넘어갑시다.